version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ollama_user
      POSTGRES_PASSWORD: ollama_pass
      POSTGRES_DB: ollama_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-network
      - scrapy-trip-dot-com_scrapy-network 

  web:
    build: .
    container_name: django-ollama
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - ollama
    networks:
      - ollama-network
      - scrapy-trip-dot-com_scrapy-network 

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    networks:
      - ollama-network
      - scrapy-trip-dot-com_scrapy-network 
    entrypoint: ["/entrypoint.sh"]

networks:
  ollama-network:
    driver: bridge
  scrapy-trip-dot-com_scrapy-network:
    external: true

volumes:
  postgres_data:
