# Generated by Django 5.1.4 on 2024-12-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(unique=True)),
                ('original_title', models.CharField(max_length=255)),
                ('rewritten_title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Hotels',
            },
        ),
    ]
